services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventario-rfid-app
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: activos_fijos
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8.4
    container_name: inventario-rfid-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: activos_fijos
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: